#!/usr/bin/env bash

export ansi_reset="\e[0m"

export ansi_black="\e[0;30m"
export ansi_red="\e[0;31m"
export ansi_green="\e[0;32m"
export ansi_yellow="\e[0;33m"
export ansi_blue="\e[0;34m"
export ansi_magenta="\e[0;35m"
export ansi_cyan="\e[0;36m"
export ansi_white="\e[0;37m"

export ansi_bold_black="\e[1;30m"
export ansi_bold_red="\e[1;31m"
export ansi_bold_green="\e[1;32m"
export ansi_bold_yellow="\e[1;33m"
export ansi_bold_blue="\e[1;34m"
export ansi_bold_magenta="\e[1;35m"
export ansi_bold_cyan="\e[1;36m"
export ansi_bold_white="\e[1;37m"

export ansi_underline_black="\e[4;30m"
export ansi_underline_red="\e[4;31m"
export ansi_underline_green="\e[4;32m"
export ansi_underline_yellow="\e[4;33m"
export ansi_underline_blue="\e[4;34m"
export ansi_underline_magenta="\e[4;35m"
export ansi_underline_cyan="\e[4;36m"
export ansi_underline_white="\e[4;37m"

export ansi_background_black="\e[0;40m"
export ansi_background_red="\e[0;41m"
export ansi_background_green="\e[0;42m"
export ansi_background_yellow="\e[0;43m"
export ansi_background_blue="\e[0;44m"
export ansi_background_magenta="\e[0;45m"
export ansi_background_cyan="\e[0;46m"
export ansi_background_white="\e[0;47m"

export ansi_bright_black="\e[0;90m"
export ansi_bright_red="\e[0;91m"
export ansi_bright_green="\e[0;92m"
export ansi_bright_yellow="\e[0;93m"
export ansi_bright_blue="\e[0;94m"
export ansi_bright_magenta="\e[0;95m"
export ansi_bright_cyan="\e[0;96m"
export ansi_bright_white="\e[0;97m"

export ansi_bold_bright_black="\e[1;90m"
export ansi_bold_bright_red="\e[1;91m"
export ansi_bold_bright_green="\e[1;92m"
export ansi_bold_bright_yellow="\e[1;93m"
export ansi_bold_bright_blue="\e[1;94m"
export ansi_bold_bright_magenta="\e[1;95m"
export ansi_bold_bright_cyan="\e[1;96m"
export ansi_bold_bright_white="\e[1;97m"

export ansi_background_bright_black="\e[1;100m"
export ansi_background_bright_red="\e[1;101m"
export ansi_background_bright_green="\e[1;102m"
export ansi_background_bright_yellow="\e[1;103m"
export ansi_background_bright_blue="\e[1;104m"
export ansi_background_bright_magenta="\e[1;105m"
export ansi_background_bright_cyan="\e[1;106m"
export ansi_background_bright_white="\e[1;107m"
