#!/usr/bin/env bash

set -e

SCRIPT_PATH="${0%/*}"
REPO_ROOT="$(git rev-parse --show-toplevel)"

###############################################################################

function build_libfmt()
{
  cd "${REPO_ROOT}/fmt"
  cmake -G Ninja
  ninja
  rm .ninja_deps .ninja_log build.ninja
  cd -
}

###############################################################################

function main()
{
  if [[ ! -r "${REPO_ROOT}/fmt/libfmt.a" ]] ; then
    build_libfmt
  fi

  time g++ -Wall -Wpessimizing-move -Wredundant-move -std=c++20 -fdiagnostics-color=always \
    -I "${REPO_ROOT}" \
    -I "${REPO_ROOT}/ut/include"  \
    -I "${REPO_ROOT}/operators/include" \
    -I "${REPO_ROOT}/fmt/include" \
    -I "${REPO_ROOT}/static_string/include" \
    -I "${REPO_ROOT}/static-string-cpp" \
    -I "${REPO_ROOT}/misc" \
    \
    "${REPO_ROOT}/memory/small-pool.cpp" \
    "${REPO_ROOT}/memory/test/test-memory.cpp" \
    -o "${REPO_ROOT}/test-memory" \
    \
    -L "${REPO_ROOT}" \
    -L "${REPO_ROOT}/fmt" \
    -l "fmt" \
    \
    && "${REPO_ROOT}/test-memory"
}

###############################################################################

main "$@"
